[package]
name = "driver"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
device = { path = "../device" }
ir = { path = "../ir" }
irparse = { path = "../irparse" }
wholeprog = { path = "../wholeprog" }
legalize = { path = "../legalize" }
callgraph = { path = "../callgraph" }
alloc = { path = "../alloc" }
isel = { path = "../isel" }
isel-pic18 = { path = "../isel-pic18" }
banking = { path = "../banking" }
peephole = { path = "../peephole" }
asm = { path = "../asm" }

[dev-dependencies]
pic14-sim = { path = "../sim" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

[[bin]]
name = "epic-cc"
path = "src/main.rs"

[lib]
name = "driver"
path = "src/lib.rs"
