[package]
name = "epic-cc-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
irparse = { path = "../crates/irparse" }

[[bin]]
name = "irparse_parse_ll"
path = "fuzz_targets/irparse_parse_ll.rs"
test = false
doc = false
