[package]
name = "isel"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ir = { path = "../ir" }

[dev-dependencies]
pic14-sim = { path = "../sim" }
asm = { path = "../asm" }
banking = { path = "../banking" }
legalize = { path = "../legalize" }

[[bin]]
name = "isel"
path = "src/bin/isel.rs"
