//! Generated device headers and the real `xc.h` (epic-cc#688, docs/46 D-3).
//!
//! Tutorial code names SFRs (`PORTB`) and bits (`PORTBbits.RB0`) the XC8
//! way, so the driver generates `pic<part>.h` from the device registry's
//! `sfrs` table and ships a real `<xc.h>` that picks it by part macro.
//! Bitfields are `unsigned char`, never `unsigned`: clang's `int` is 16
//! bits on this target, so an `unsigned` member would span two registers.

use std::collections::{BTreeMap, HashSet};

use device::{Device, Sfr};

/// The clang part macro for a device: `p16f877a` reads `_16F877A`. Shared
/// with `predef` so the `xc.h` dispatch below tests the macro the driver
/// actually defines.
pub fn part_macro(name: &str) -> String {
    format!("_{}", name.strip_prefix('p').unwrap_or(name).to_uppercase())
}

/// The shipped filename for a device: `p16f877a` reads `pic16f877a.h`.
pub fn pic_filename(device: &Device) -> String {
    format!(
        "pic{}.h",
        device.name.strip_prefix('p').unwrap_or(device.name)
    )
}

/// The generated header for a device, or `None` when it carries no `sfrs`
/// table. `None` parts get a naming `#error` in `xc.h` instead.
pub fn pic_header(device: &Device) -> Option<String> {
    if device.sfrs.is_empty() {
        return None;
    }
    let stem = device.name.strip_prefix('p').unwrap_or(device.name);
    let mut out = String::new();
    out.push_str(&format!("#ifndef PIC{}_H\n", stem.to_uppercase()));
    out.push_str(&format!("#define PIC{}_H\n", stem.to_uppercase()));
    out.push_str("\n/* Generated by epic-cc from Microchip DFP data\n");
    out.push_str(" * (Apache-2.0, ADR-029). Do not edit. */\n");
    out.push_str("#include <stdint.h>\n");
    let taken = macro_names(device);
    for sfr in device.sfrs {
        emit_register(&mut out, sfr, &taken);
    }
    emit_aliases(&mut out, device);
    out.push_str("\n#ifndef NO_BIT_DEFINES\n");
    out.push_str("/* Bare bit names (RB0) stay out: object-like macros expand after\n");
    out.push_str(" * `.`, so `#define RB0 ...` breaks `PORTBbits.RB0` (epic-cc#707).\n");
    out.push_str(" * They return with a real bit entity; keep passing NO_BIT_DEFINES\n");
    out.push_str(" * to ignore that future spelling. */\n");
    out.push_str("#endif /* NO_BIT_DEFINES */\n");
    out.push_str(&format!("\n#endif /* PIC{}_H */\n", stem.to_uppercase()));
    Some(out)
}

/// Every macro the header defines: registers, aliases, bits variables and
/// their types. A bitfield member with one of these names (the pack names
/// a 5-bit field `PCLATH` inside register `PCLATH`) would expand inside
/// its own struct, so members and bare bits both skip this set.
fn macro_names(device: &Device) -> HashSet<String> {
    let mut taken = HashSet::new();
    for sfr in device.sfrs {
        taken.insert(sfr.name.to_string());
        for alias in sfr.aliases {
            taken.insert(alias.to_string());
        }
        if sfr.width == 1 && !sfr.fields.is_empty() {
            taken.insert(format!("{n}bits", n = sfr.name));
            taken.insert(format!("{n}bits_t", n = sfr.name));
            for alias in sfr.aliases {
                taken.insert(format!("{alias}bits"));
            }
        }
    }
    taken
}

fn addr(sfr: &Sfr) -> String {
    format!("{:#05X}", sfr.addr)
}

fn emit_register(out: &mut String, sfr: &Sfr, taken: &HashSet<String>) {
    let a = addr(sfr);
    match sfr.width {
        1 => out.push_str(&format!(
            "\n#define {n} (*(volatile unsigned char *){a})\n",
            n = sfr.name
        )),
        2 => out.push_str(&format!(
            "\n#define {n} (*(volatile uint16_t *){a})\n",
            n = sfr.name
        )),
        3 => return,
        w => panic!("headers: unsupported SFR width {w} for {}", sfr.name),
    }
    if sfr.width != 1 || sfr.fields.is_empty() {
        return;
    }
    let mut modes: BTreeMap<u8, Vec<_>> = BTreeMap::new();
    for f in sfr.fields {
        modes.entry(f.mode).or_default().push(f);
    }
    out.push_str("typedef union {\n");
    for fields in modes.values() {
        let mut sorted = fields.clone();
        sorted.sort_by_key(|f| f.shift);
        out.push_str("  struct {\n");
        let mut cursor = 0u8;
        for f in sorted {
            let width = f.mask.count_ones() as u8;
            if f.shift > cursor {
                out.push_str(&format!("    unsigned char : {};\n", f.shift - cursor));
            }
            if taken.contains(f.name) {
                out.push_str(&format!("    unsigned char : {width};\n"));
            } else {
                out.push_str(&format!("    unsigned char {n} : {width};\n", n = f.name));
            }
            cursor = f.shift + width;
        }
        if cursor < 8 {
            out.push_str(&format!("    unsigned char : {};\n", 8 - cursor));
        }
        out.push_str("  };\n");
    }
    out.push_str(&format!("}} {n}bits_t;\n", n = sfr.name));
    out.push_str(&format!(
        "#define {n}bits (*(volatile {n}bits_t *){a})\n",
        n = sfr.name
    ));
}

fn emit_aliases(out: &mut String, device: &Device) {
    for sfr in device.sfrs {
        if sfr.width != 1 && sfr.width != 2 {
            continue;
        }
        for alias in sfr.aliases {
            out.push_str(&format!("\n#define {alias} {n}\n", n = sfr.name));
            if sfr.width == 1 && !sfr.fields.is_empty() {
                out.push_str(&format!("#define {alias}bits {n}bits\n", n = sfr.name));
            }
        }
    }
}

/// The real `<xc.h>`: picks the generated per-device header by part macro,
/// then the tutorial delay surface over the cycle-exact `_delay` intrinsic
/// (epic-cc#700). Parts without an `sfrs` table name themselves in an
/// `#error`; an unrecognized macro falls through to the generic one.
pub fn xc_h() -> String {
    let mut out = String::new();
    out.push_str("#ifndef _XC_H\n#define _XC_H\n");
    out.push_str("\n/* Generated by epic-cc (docs/46 D-3). Define _XTAL_FREQ\n");
    out.push_str(" * before using __delay_ms/__delay_us, the XC8 tutorial spelling. */\n");
    let mut first = true;
    for dev in device::ALL {
        if dev.sfrs.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "{}if defined({m})\n#include \"{f}\"\n",
            if first { "#" } else { "#el" },
            m = part_macro(dev.name),
            f = pic_filename(dev)
        ));
        first = false;
    }
    for dev in device::ALL {
        if !dev.sfrs.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "#elif defined({m})\n#error \"epic-cc: no device header for {n} (no SFR table)\"\n",
            m = part_macro(dev.name),
            n = dev.name
        ));
    }
    out.push_str("#else\n#error \"epic-cc: no device header for the selected part\"\n#endif\n");
    out.push_str("\n/* Instruction-cycle delays: one millisecond is Fosc/4000\n");
    out.push_str(" * cycles, one microsecond Fosc/4000000. */\n");
    out.push_str("void _delay(unsigned long cycles);\n");
    out.push_str("#define __delay_ms(x) _delay((unsigned long)((x) * (_XTAL_FREQ / 4000.0)))\n");
    out.push_str("#define __delay_us(x) _delay((unsigned long)((x) * (_XTAL_FREQ / 4000000.0)))\n");
    out.push_str("\n#endif /* _XC_H */\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dev(name: &str) -> &'static Device {
        device::by_name(name).unwrap()
    }

    #[test]
    fn part_macro_strips_the_leading_p() {
        assert_eq!(part_macro("p16f877a"), "_16F877A");
        assert_eq!(part_macro("p18f4550"), "_18F4550");
    }

    #[test]
    fn pic_filename_carries_the_pic_prefix() {
        assert_eq!(pic_filename(dev("p16f877a")), "pic16f877a.h");
    }

    #[test]
    fn header_without_a_table_is_none() {
        assert!(pic_header(dev("p12f509")).is_none());
    }

    #[test]
    fn registers_use_byte_defines_and_char_bitfields() {
        let h = pic_header(dev("p16f877a")).unwrap();
        assert!(h.contains("#define PORTB (*(volatile unsigned char *)0x006)"));
        assert!(h.contains("unsigned char RB0 : 1;"));
        assert!(
            !h.contains("unsigned RB0"),
            "an unsigned member would span two registers"
        );
    }

    #[test]
    fn joined_sixteen_bit_registers_use_u16() {
        let h = pic_header(dev("p16f877a")).unwrap();
        assert!(h.contains("#define TMR1 (*(volatile uint16_t *)0x00E)"));
        assert!(h.contains("#include <stdint.h>"));
    }

    #[test]
    fn three_byte_joined_registers_are_skipped() {
        let h = pic_header(dev("p18f4550")).unwrap();
        assert!(!h.contains("#define TBLPTR ("));
        assert!(h.contains("#define TBLPTRL ("));
        assert!(h.contains("#define TBLPTRH ("));
        assert!(h.contains("#define TBLPTRU ("));
    }

    #[test]
    fn members_named_like_their_register_are_skipped() {
        let h = pic_header(dev("p16f877a")).unwrap();
        assert!(
            !h.contains("unsigned char PCLATH :"),
            "the 5-bit PCLATH field would expand the register macro inside its own struct"
        );
        assert!(h.contains("#define PCLATH ("));
    }
    #[test]
    fn skipped_members_hold_their_bits_as_padding() {
        let h = pic_header(dev("p16f1937")).unwrap();
        let end = h.find("} CCP1ASbits_t;").unwrap();
        let start = h[..end].rfind("typedef union {").unwrap();
        let mode0 = h[start..end].split("};").next().unwrap();
        let hole = mode0.find("unsigned char : 3;").unwrap();
        let ase = mode0.find("unsigned char CCP1ASE : 1;").unwrap();
        assert!(hole < ase, "CCP1ASE must sit past the skipped 3-bit field");
    }

    #[test]
    fn aliases_of_skipped_registers_are_dropped() {
        let h = pic_header(dev("p18f4550")).unwrap();
        assert!(
            !h.contains("#define PC PCLAT"),
            "PCLAT has no header define"
        );
    }
    #[test]
    fn legacy_aliases_cover_register_and_bits() {
        let h = pic_header(dev("p18f4550")).unwrap();
        assert!(h.contains("#define DDRA TRISA"));
        assert!(h.contains("#define DDRAbits TRISAbits"));
    }

    #[test]
    fn bare_bits_stay_out_until_a_real_bit_entity_lands() {
        let h = pic_header(dev("p16f877a")).unwrap();
        assert!(h.contains("#ifndef NO_BIT_DEFINES"));
        assert!(
            !h.contains("#define RB0 PORTBbits"),
            "macros expand after `.`"
        );
    }
    #[test]
    fn xc_h_dispatches_by_part_macro_and_names_table_less_parts() {
        let h = xc_h();
        assert!(h.contains("#if defined(_12F675)"));
        assert!(h.contains("defined(_16F877A)"));
        assert!(h.contains("#include \"pic16f877a.h\""));
        assert!(h.contains("#include \"pic18f4550.h\""));
        assert!(h.contains("_12F509"));
        assert!(h.contains("no device header for p12f509"));
        assert!(h.contains("__delay_ms"));
        assert!(h.contains("__delay_us"));
        assert!(h.contains("void _delay(unsigned long cycles);"));
    }
}
